const express = require('express')
const app = express()
const mongoose = require('mongoose')
const dotenv = require('dotenv')
const cors = require('cors')

const authRoute = require('./routes/auth')
const userRoute = require('./routes/user')
const productRoute = require('./routes/product')
const cartRoute = require('./routes/cart')
const orderRoute = require('./routes/order')
const stripeRoute = require('./routes/stripe')

dotenv.config()
mongoose
  .connect(process.env.mongo_url)
  .then(() => console.log('mongodb connected'))
  .catch((err) => {
    console.log(err)
  })
app.use(express.json())
app.use(cors())
app.use('/api/auth', authRoute)
app.use('/api/users', userRoute)
app.use('/api/products', productRoute)
app.use('/api/cart', cartRoute)
app.use('/api/order', orderRoute)
app.use('/api/checkout', stripeRoute)
app.listen(process.env.PORT || 5000, () => {
  console.log('server is running !')
})
